# Generated by Django 5.2.9 on 2025-12-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Django博客', max_length=200, verbose_name='网站标题')),
                ('site_description', models.TextField(blank=True, verbose_name='网站描述')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='背景图片')),
                ('active_theme', models.CharField(choices=[('default', '默认主题'), ('dark', '暗黑主题'), ('light', '明亮主题')], default='default', max_length=20, verbose_name='当前主题')),
            ],
            options={
                'verbose_name': '博客设置',
                'verbose_name_plural': '博客设置',
            },
        ),
    ]
